apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: kkkk
  namespace: argocd
spec: 
  destination: 
    namespace: argocd
    server: "https://kubernetes.default.svc"
  project: default
  source:
    path: newtry
    repoURL: "git@github.com:venkata221/temp-graphql-ts.git"
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
